

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Open Doc
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


- name: ROBOTSHOP -              🌏 Get DEMO UI LOGINS
  shell: |
    appURL=$(oc get routes -n robot-shop web  -o jsonpath="{['spec']['host']}")|| true

    export URL=http://$appURL
    if [ -x "$(command -v open)" ]; then
      open $URL
    else 
      if [ -x "$(command -v firefox)" ]; then
        firefox $URL
      else 
        if [ -x "$(command -v google-chrome)" ]; then
          google-chrome $URL
        fi
      fi
    fi
  ignore_errors: yes
  register: LOGINS


- name: ROBOTSHOP -              🟢 ROBOTSHOP
  debug: 
    var: LOGINS.stdout_lines
