#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS v3.4.0
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - IBM Operator
#  - AI Manager
#  - OpenLDAP & Register with AI Manager
#  - RobotShop Demo App
#  - Demo Service Account 
#  - AWX (Open Source Ansible Tower) with preloaded Playbooks
#  - Disables ASM Service match rule 
#  - Train Models
#    - Create Training Definitions (TG, LAD, CR, SI. Turn off RSA) 
#    - Create Training Data (LAD, SNOW) 
#    - Train Models (TG, LAD, CR, SI) 
#  - Topology
#    - Create K8s Observer
#    - Create ASM merge rules
#    - Load ASM merge Topology
#    - Create AI Manager Application
#  - Creates valid certificate for Ingress (Slack) 
#  - External Routes (Flink, Topology, ...)
#  - Disables ASM Service match rule 
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 

- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4waiops.yaml

  roles:  

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INITIALIZATION
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Placeholder for customization
    - role: 00_init-custom-hook

# Initialize Logging
    - role: 01_init-logging
    
    - role: 02_init_checks
# Start block
    - role: 98-log-start-01

# Run Prerequisites
    - role: 03_init-initialization
  
    - role: 04_storage-rook-ceph
      when: (ROOK_CEPH_INSTALL_MODE=="enable" or ROOK_CEPH_INSTALL_MODE=="automatic") and  INSTALL_ROOK_CEPH=="true"

    - role: 05_init-get-storage-class
      
#     - role: 06_aimanager-prerequisites
      


