
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Connection Details
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Get Cluster FQDN
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


- name: LOGIN -                  🚀 WAIOPS - Get Logins (please ignore any errors)
  shell: |
    ../tools/20_get_logins.sh > ../LOGINS.txt
  ignore_errors: yes


- name: LOGIN -                  🚀 WAIOPS - Print Logins
  shell: |
    cat ../LOGINS.txt
  ignore_errors: yes



